# Generated by Django 3.0.4 on 2020-04-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_auto_20200410_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Question',
            new_name='question',
        ),
    ]
